version: "3.7"

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "5000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"