// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package products

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID        int32
	Name      string
	Price     pgtype.Numeric
	Available pgtype.Bool
	Created   pgtype.Timestamp
}
